### ISSUE TITLE
Resizing window can lead to crash

### ISSUE THREAD

**Issue by ForGorNorPor** [db0/godot-card-game-framework#133]
Resizing the game window to the smallest width results in a crash when having a full hand. This happens in the function `_get_oval_angle_by_index` in line 2207
`card_angle= rad2deg(atan(- ver_rad / hor_rad / tan(deg2rad(angle))))` because `hor_rad` is 0.

**Comment by db0** [comment]
I just tried it myself, but I couldn't get it to crash. How exactly did you resize the game window? Also, which OS?

**Comment by ForGorNorPor** [comment]
The repro on my machine is:
1. Run game from editor via F5
2. Repeatedly click on the card stack in the lower left corner until you have the maximum of cards
3. Drag the right window edge over to the left as far as you can

OS: Win 8.1

**Comment by db0** [comment]
Great (or not so great 😄)! I can reproduce it now
