### ISSUE TITLE
When having multiple hand on the board, card rotation not calculated.

### ISSUE THREAD

**Issue by fengjiongmax** [db0/godot-card-game-framework#142]
In a scene have two sets of deck, hand, discard. Like this:
![image](https://user-images.githubusercontent.com/5288733/119222737-6905b600-bb28-11eb-8a62-f7079125f740.png)
And then everything is set up correctly, like draw card from OpponentDeck will draw a card to OpponentHand. 

But after a card draw from OpponentDeck, cards in OpponentHand do not rotate, as shown in this gif:
![card_rotate](https://user-images.githubusercontent.com/5288733/119223073-f09ff480-bb29-11eb-89f9-316ced4ce745.gif)
I've created a branch to reproduce this:https://github.com/fengjiongmax/godot-card-game-framework/tree/multiple-hand-debug

After digging into the code, I think the line causing this is:
https://github.com/db0/godot-card-game-framework/blob/2d20e268ddaaba844a9ba761b6f82740589979f0/src/core/CardTemplate.gd#L2498

I guess this can be solved by replacing `get_parent() == cfc.NMAP.hand` with `get_parent().is_in_group("hand")`.

**Comment by db0** [comment]
Yeah that looks like it's the issue for sure :)
