### ISSUE TITLE
Errors while importing Godot Card Manager using AssetLib...

### ISSUE THREAD

**Issue by richhl** [db0/godot-card-game-framework#146]
any clue? Thx in advance.

Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Gallium 0.4 on AMD ICELAND (DRM 3.8.0 / 4.9.0-8-amd64, LLVM 3.9.1)
OpenGL ES Batching: ON
/usr/lib/x86_64-linux-gnu/libpulse.so.0: undefined symbol: pa_threaded_mainloop_once_unlocked
/usr/lib/x86_64-linux-gnu/libpulse.so.0: undefined symbol: pa_thread_make_realtime
 
ERROR: _parse_url: Malformed URL:  	https://raw.githubusercontent.com/Anaxie-Studio/godot-better-animated-texture/main/icon.png.
   At: scene/main/http_request.cpp:63.
ERROR: store_buffer: Condition "!p_src" is true.
   At: drivers/unix/file_access_unix.cpp:279.
ERROR: store_buffer: Condition "!p_src" is true.
   At: drivers/unix/file_access_unix.cpp:279.
SCRIPT ERROR: GDScript::reload: Parse Error: Variable "i" already defined in the scope (at line 136).
   At: res://cards.gd:139.
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583.
ERROR: load_source_code: Condition "err" is true. Returned: err
   At: modules/gdscript/gdscript.cpp:813.
ERROR: load: Cannot load source code from file 'res://scripts/cards.gd'.
   At: modules/gdscript/gdscript.cpp:2239.
ERROR: _load: Failed loading resource: res://scripts/cards.gd. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282.
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://scripts/cards.gd
   At: res://main.gd:3.
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583.

**Comment by db0** [comment]
CGF is not in the Asset Library. It only exists in the templates under the project manager and I just tested that and works fine. Are you sure you're not downloading something else?

**Comment by richhl** [comment]
Then i'm not supposed to install as shown in image?

![imagen](https://user-images.githubusercontent.com/1074446/124932134-1b270d80-e003-11eb-8293-b45ab4e6bc17.png)

**Comment by db0** [comment]
That's not the "Card Game Framework". This is something else completely that someone else made and probably abandoned. :D
