### ISSUE TITLE
Help with QUICKSTART process. Not able to find Script Variables...

### ISSUE THREAD

**Issue by richhl** [db0/godot-card-game-framework#148]
Would you please give me advice....stuck when trying to reach step 8....

7. Find and Right click on res://src/core/Main.tscn and select "New Inherited Scene". A new unsaved scene will open. DONE!
8. In the inspector, under "Script Variables", click on "[empty]" next to Board Scene, then "load" then navigate to your res://src/new_card_game/Board.tcsn HOW?
![imagen](https://user-images.githubusercontent.com/1074446/125076261-fd6bae00-e0bf-11eb-8839-162cbed698ff.png)

Thx in advance!.

**Comment by db0** [comment]
For this kind of questions, please join the discord channel instead of opening issues. https://discord.gg/KFKHt6Ch
