### ISSUE TITLE
All the custom fonts are missing

### ISSUE THREAD

**Issue by Cwpute** [db0/godot-card-game-framework#154]
Every custom font is missing from the project, thus leaving the game text-less: 
![cgf issue1](https://user-images.githubusercontent.com/80604512/132880221-9576f368-924a-4390-8ae2-083f295f41d9.png)

The console shows :
![cgf issue2](https://user-images.githubusercontent.com/80604512/132880330-3a8dae5e-2b72-42b0-969c-a79995768608.png)

I downloaded each font again ([ReggaeOneRegular](https://github.com/fontworks-fonts/Reggae/blob/master/fonts/ttf/ReggaeOne-Regular.ttf), [Comfortaa Bold](https://fontlibrary.org/font/en/comfortaa-bold), [Xolonium Regular](https://fontlibrary.org/en/font/xolonium), [ReenieBeanie Regular](https://fonts.google.com/specimen/Reenie+Beanie)) and placed them in their respective directories, where they should have been. And the framework now displays like it should... i guess :thinking: 

Were they excluded by accident some way or another ?
Or was it intentional ? if so, the tutorial should probably account for it. I'm going through it myself and, i'm not engaged very deep into it, but i might fork and request a push with modifications later, since it seems it needs updating.

**Comment by db0** [comment]
Is this when imported into your own project, or when cloning CGF directly? because it is working fine on my end.

**Comment by Cwpute** [comment]
i downloaded the "code" zip file from github: 
![screen](https://user-images.githubusercontent.com/80604512/132925329-d4fa5096-418e-4c9c-9c42-519e065bd9d6.png)

**Comment by db0** [comment]
Hm, weird. Can you try to clone with git instead?

**Comment by db0** [comment]
I just downloaded the code zip, and also working fine for me.

**Comment by Cwpute** [comment]
I tried downloading it too and it worked as well :( fonts and all, everything was where it was supposed to be.
Maybe my download failed somehow the first time around. Sorry for the inconvenience !
