### ISSUE TITLE
Plugin cannot be activated

### ISSUE THREAD

**Issue by Cwpute** [db0/godot-card-game-framework#155]
Whenever i open up the project, Godot shows a message (roughly translatable to) : 
`Can't activate plugin from : « res://addons/gut/plugin.cfg », syntax analyse of the configurations failed.`

I opened up [another issue](https://github.com/db0/godot-card-game-framework/issues/154) about fonts previously, i'm suspecting this series of bug is of my own doing but i can't say where I did things wrong, so i'll keep opening issues if that's not... an issue :eyes:

**Comment by db0** [comment]
Yes, this is only coming first type you open the project in Godot. Somehow caused by GUT but you can ignore it.
