### ISSUE TITLE
Addendum to the AGPL3 to allow use of Steam SDK

### ISSUE THREAD

**Issue by db0** [db0/godot-card-game-framework#159]
Hey everyone, my purpose for this framework has always been to enable people to make games as easy as possible and to ensure that their contributions are also passed back into the commons in turn.

However we cannot discount the reach of platforms like Steam and as we would like to allow anyone making games [using this framework the possibility to distribute them via Steam and make use of its multiplayer capabilities](https://partner.steamgames.com/doc/sdk/uploading/distributing_opensource), we decided to expand the license with [a small addendum](https://github.com/db0/godot-card-game-framework/blob/main/ADDENDUM1), which explicitly allows the use of Steamworks SDK.

If you've contributed to this project in the past, please let us know if you are opposed to this change. If so, we'll have to remove your code contributions to proceed.

I'm pinging all contributors below:
@vmjcv 
@zombieCraig 
@richhl 
@stevosaurus 
@fengjiongmax 
@EasternMouse 

Please let me know within a month if you disagree with this change, otherwise I will assume you're all in agreement.

Feel free to discuss the wording of the addendum or if you have any better idea to allow the use of the Steamworks SDK.

**Comment by stevosaurus** [comment]
I'm in favor of the addendum, please feel free to include my contributions.

**Comment by fengjiongmax** [comment]
In favor +1

**Comment by vmjcv** [comment]
In favor +1

**Comment by EasternMouse** [comment]
In favor +1

**Comment by db0** [comment]
Thanks everyone!
